### ISSUE TITLE
Java11/17/21 & Hadoop 3.4.1 & Hive 4.0.1 Support

### ISSUE THREAD

**Issue by adamdec0173** [HiveRunner/HiveRunner#180]
**Is your feature request related to a problem? Please describe.**
Use HiveRunner library in Java21 and newest version of Hadoop/Hive dependencies

**Describe the solution you'd like**
I have a solution that works if anyone is interested?

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by massdosage** [comment]
If you have a solution we'd be interested in seeing it, can you raise a PR with your changes and we'll take a look?

**Comment by adamdec0173** [comment]
May I send a zip?

**Comment by massdosage** [comment]
Implemented in new `hive-4.x` branch via #181
