### ISSUE TITLE
Create view

### ISSUE THREAD

**Issue by cgmuros** [HiveRunner/HiveRunner#52]
Hi, I have a hql script where I create a View, but when I execute this script I receive an error. HiveRunner supports Views Objects? 

Here my code

```
    @HiveSQL(files = {
        "scripts/one.hql",
        "scripts/two.hql",
        "scripts/three.hql" }, autoStart = false)
private HiveShell hiveShell;



@Before
public void before() {
    hiveShell.addSetupScript("create database cdeexp");
    hiveShell.addSetupScript("create database rdmexp");
    hiveShell.setHiveConfValue("var", "${hiveconf:hadoop.tmp.dir}");
    hiveShell.setHiveConfValue("PATH_AMBIENTE", "${hiveconf:hadoop.tmp.dir}");
    hiveShell.start();
    hiveShell.executeQuery("use cdeexp");
}

   @Test
public void testview() {
    hiveShell.executeQuery("use rdmexp");

    hiveShell.execute(new File("src/main/hive/ddl/vistas/view.hql"));

    String tabla = "view";
    List<String> actual = hiveShell.executeQuery("show tables like '"+ tabla + "'");
    Assert.assertEquals(actual.get(0), tabla);
}
```

The error occurs when hiverunner execute the hive.hql (testview method). The script view.hql contains join between the first tables. 

Thanks for your help,

**Comment by jorgenfalk** [comment]
I can't reproduce this. I used a implicit join without any issues. (See ViewTest.java in https://github.com/klarna/HiveRunner/tree/Issue52_Create_View)

Could you share your code for the join (view.hql)?

**Comment by cgmuros** [comment]
jorgenfalk, I tried to upload the class and hql files into branch but I couldn't. Attach a zip with hql and java class. 

Thanks for your help.

[view_fail.zip](https://github.com/klarna/HiveRunner/files/498923/view_fail.zip)

**Comment by jorgenfalk** [comment]
I briefly tried you're code and got some syntax issues. Haven't have the time to dig into it, but your code looks OK. Is this the errors you get:

ERROR   [ViewFailTest#vw_utp_cliente_bco_stgo_dia]    hive.ql.metadata.Hive    - Table CDE_DT_PERSONA not found: CDEEXP.CDE_DT_PERSONA table not found

(And I need to double check: did you verify that your code works in Hive? If so, what version of Hive)

**Comment by jorgenfalk** [comment]
The "table not found"-error is from the DROP IF EXISTS statements. Hive has implemented IF EXISTS as a try-catch statement.

**Comment by jorgenfalk** [comment]
I think I've figured this out. I believe it's the same issue as with the CTE bug reported earlier. When it comes to VIEWs, Hive can't really decide on if it is case sensitive or not. Some parts of the code is, some isn't. The Hive CLI seems to just flatten this out by running toLowerCase() on everything.

What you have to do is either to add aliases to your table names (use lowercase letters) or change all names to lowercase.

**Comment by jorgenfalk** [comment]
I updated my test case in this branch to show the issue and possible solutions. 

A similar issue is already reported in Hive (https://issues.apache.org/jira/browse/HIVE-10698). Should be solved in Hive 1.3 and 2.0. Current version of HIveRunner use Hive 1.2

**Comment by cgmuros** [comment]
jorgenfalk, thanks for your answer. So, let me see if I undertood. I have to wait for Hiverunner's update to 1.3?

Regards,

**Comment by jorgenfalk** [comment]
If possible, you can change your table names / identifiers to lowercase or add name alias. Please look at the test case I created: https://github.com/klarna/HiveRunner/blob/Issue52_Create_View/src/test/java/com/klarna/hiverunner/ViewTest.java

But if that is not possible, you have to wait for HiveRunner to use Hive1.3 (or 2.x).

**Comment by cgmuros** [comment]
Thanks for your help
